2025-10-30 08:27:54,940 - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2025-10-30 08:27:54,940 - INFO - NumExpr defaulting to 8 threads.
2025-10-30 08:28:10,641 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-69' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at C:\Users\ACER\AppData\Roaming\Python\Python312\site-packages\tornado\websocket.py:1086> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Roaming\Python\Python312\site-packages\streamlit\web\bootstrap.py", line 348, in run
    if asyncio.get_running_loop().is_running():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Roaming\Python\Python312\site-packages\tornado\websocket.py", line 1088, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Roaming\Python\Python312\site-packages\tornado\websocket.py", line 1090, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
